### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by randiyasen** [thiwaK/m3u8_downloader#1]
**Error message displays when login.** 

Message : Check your mobile number
Installed python to PATH : python 3.11

( I think heroku applications are not working. Try posting them on different service )

**Comment by thiwaK** [comment]
The error msg you are referring to indicates that you are entering your mobile number in a non-international format. You can fix this by replacing the leading 0 of your mobile number with +94 (ex: 077123456 → +9477123456). This will fix the error, but as this repo has not been maintained for a long time, the program may not work as it should. 

And yes, APIs are down 🙂
